# Generated by Django 4.0.3 on 2022-07-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_alter_post_forum_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='image',
            field=models.TextField(default='test image'),
            preserve_default=False,
        ),
    ]
