# Generated by Django 4.0.3 on 2022-07-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
