# Generated by Django 4.0.3 on 2022-04-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_profiles', '0005_remove_contactus_staff_group_profile_staff_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePasswordKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_key', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
