# Generated by Django 4.0.3 on 2022-04-13 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage_profiles', '0006_changepasswordkeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='changepasswordkeys',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
