# Generated by Django 4.0.3 on 2022-04-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_profiles', '0007_changepasswordkeys_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
