# Generated by Django 4.0.3 on 2022-07-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_profiles', '0010_appuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(default=120),
        ),
    ]
